name: Benson Creative
favicon: null
layout_spectrum: 0.25056
typography_spectrum: 0.38649
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fdfdff'
    - '#d7d7d7'
    - '#5b504d'
    - '#1e1c1a'
    - '#7a8a00'
  brandStrength: 0.9250179247464985
  lightness: 0.7975868531502783
  saturation: 0.3806859692558646
  rhythmicContrast: 0.25
purpose: []
